# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build Application'
    steps:
    - script: echo "Building the application"

- stage: Test
  jobs:
  - job: TestJob
    displayName: 'Test Application'
    steps:
    - script: echo "Running tests"

- stage: Deploy
  jobs:
  - job: DeployJob
    displayName: 'Deploy Application'
    steps:
    - script: echo "Deploying the application"

