name: $(BuildDefinitionName) $(SourceBranchName) $(date:yyyy).$(date:MM).$(date:dd) $(Rev:.r)

##############################################################
#  Pipeline Practice - Conditions + Variables + JobStatus Check Fcts + Task inputs
##############################################################

trigger: none 

## Conditions has different types ( 1-Built-in condition , 2-Custom Conditions , 3-Compond Conditions) ##

stages:
- stage: stage1
  jobs:
  
  ## 1-Built-in condition ##
  # Branch Condition #
  - job: job1
    condition: eq(variables['Build.SourceBranch'] , 'master')
    steps:
    - script: echo "Hello Job 1"

