# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo "Building the application"
      diplayName : 'Build Application'

- stage: Test
  jobs:
  - job: TestJob
    steps:
    - script: echo "Running tests"
      diplayName : 'Test Application'

- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - script: echo "Deploying the application"
      diplayName : 'Deploy Application'

