name: $(BuildDefinitionName) $(SourceBranchName) $(date:yyyy).$(date:MM).$(date:dd) $(Rev:.r)

##############################################################
#  Pipeline Practice - Conditions + Variables + JobStatus Check Fcts + Task inputs
##############################################################

trigger:
  branches:
    include:
      - main 

## Conditions has different types ( 1-Built-in condition , 2-Custom Conditions , 3-Compond Conditions) ##

stages:
- stage: stage1
  jobs:
  
  ## 1-Built-in condition ##
  # Branch Condition #
  - job: job1
    displayName: Branch Condition
    condition: eq(variables['Build.SourceBranch'] , 'refs/heads/main')
    steps:
    - script: echo "Hello Job 1"

  # Build trigger Condition #
  - job: job2
    displayName: trigger Condition
    condition: eq(variables['Build.Reason'] , 'Manual')
    steps:
    - script: echo "Hello Job 1"