trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Java Application'
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '11'
      addToPath: true

  - script: |
      cd $(Build.SourcesDirectory)/java_application
      javac -d $(Build.BinariesDirectory)/classes src/*.java
    displayName: 'Compile Java Code'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)/Application_java'
      Contents: '**'
      TargetFolder: '$(Build.BinariesDirectory)/classes'
    displayName: 'Copy HTML files'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.BinariesDirectory)/classes'
      includeRootFolder: false
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Archive Artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'java-app'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'
