name: $(BuildDefinitionName) $(SourceBranchName) $(date:yyyy).$(date:MM).$(date:dd) $(Rev:.r)

##############################################################
#  Pipeline Practice
##############################################################

trigger: none 

## Parameters ##
## Parametres can be used with Template or Configuartion a Job ##
# Param with a Job #

parameters:
  - name: param1
    displayName: Param1
    type: string
    default: default value
    values:
      - value1
      - value2

stages:
- stage: stage1
  jobs:
  - job: job1
    steps:
    - script: echo "Hello ${{parameters.param1}}"

  - job: job2
    steps:
    - template: templates/template1.yaml   


      



## Conditions -- All 3 types ##
## Variables  ##
## Job Status Check Fcts ##
## Each Keyword ##
## Templates ##
## Inputs ##
## Arguments ##

